"""
``atasks.commands.service`` command-line runner tests
"""
import asyncio
import os
from contextlib import redirect_stdout
from io import StringIO
from tempfile import TemporaryDirectory
from unittest import IsolatedAsyncioTestCase as TestCase
from unittest.mock import patch

import atasks.cli as cli_module
import atasks.commands.service as run_module
from atasks.commands.service import aiomain, main
from atasks.transport.base import LoopbackTransport


def _ns(name, **overrides):
    """
    Build one namespace options dict exactly as ``aiomain()`` expects it -
    i.e. what ``_parse_namespace_spec()`` would return for ``name=<name>`` -
    for tests that call ``aiomain()`` directly instead of going through
    ``main()``'s command-line parsing (covered separately by
    test_011_run_router_options.py).
    """
    spec = {
        'name': name,
        'mode': 'client',
        'transport': 'loopback',
        'url': None,
        'hostname': None,
        'max_trace_depth': None,
        'trace_filter_modules': None,
        'collect_await_frames': None,
    }
    spec.update(overrides)
    return spec


async def _stop_soon(delay=0.05):
    """
    Flip ``run_module.exit_run`` shortly after being scheduled - stands in for
    an external SIGINT/SIGQUIT/SIGTERM (see ``sig_handler()``) so a 'server'
    namespace's "Listening for requests" wait loop in ``aiomain()`` returns
    instead of blocking the test forever. Real signal delivery against a
    background ``python -m atasks.commands.service`` process is covered separately by
    test_009_run_shutdown.py.
    """
    await asyncio.sleep(delay)
    run_module.exit_run = True


class ModuleTest(TestCase):
    """Module tests"""

    async def asyncSetUp(self):
        """A previous test's (or signal's) exit_run=True must never leak into the next one."""
        run_module.exit_run = False

    def test_run_client_mode_via_cli_calls_nothing(self):
        """A 'client'-only run (the default when no -N is given at all) must
        complete and return - it never activates a Router, so it can never
        end up waiting for a signal."""
        main(['service.py', '--verbosity=3'])

    def test_cli_service_forwards_arguments_to_runner(self):
        """The top-level ``service`` command delegates to the established runner."""
        with patch('atasks.commands.service.main') as service_main:
            cli_module.main(['atasks', 'service', 'example.tasks', '--verbosity=3'])

        service_main.assert_called_once_with(
            ['atasks service', 'example.tasks', '--verbosity=3']
        )

    def test_cli_refs_generates_references_from_relative_module_path(self):
        """The refs command derives task names relative to its working directory."""
        source = '''\
from atasks.tasks import atask, atask_broadcast, atask_queue

@atask
async def add():
    pass

@atask_queue(namespace='workers')
async def send_email():
    pass

@atask_broadcast(name='cache.clear')
async def invalidate_cache():
    pass
'''
        with TemporaryDirectory() as directory:
            package = os.path.join(directory, 'app')
            os.mkdir(package)
            source_path = os.path.join(package, 'tasks.py')
            with open(source_path, 'w', encoding='utf-8') as source_file:
                source_file.write(source)
            previous_directory = os.getcwd()
            try:
                os.chdir(directory)
                cli_module.main(['atasks', 'refs', 'app/tasks.py'])
            finally:
                os.chdir(previous_directory)

            with open(os.path.join(package, 'tasks_refs.py'), encoding='utf-8') as references_file:
                references = references_file.read()

        self.assertEqual(references, (
            '# Generated by atasks refs from %s.\n'
            '# This file contains lightweight references to the tasks declared there.\n'
            '# Do not edit this file: changes will be overwritten by the next generation.\n'
            '\n'
            'from atasks.refs import atask_bref, atask_qref, ataskref\n'
            '\n'
            "add = ataskref['app.tasks.add']\n"
            "send_email = atask_qref(namespace='workers')['app.tasks.send_email']\n"
            "invalidate_cache = atask_bref['cache.clear']\n"
        ) % source_path)

    def test_cli_refs_source_module_override_controls_default_atask_names(self):
        """A ``SOURCE=MODULE`` argument controls default atask names for that source."""
        with TemporaryDirectory() as directory:
            source_path = os.path.join(directory, 'tasks.py')
            with open(source_path, 'w', encoding='utf-8') as source_file:
                source_file.write('@atask\nasync def work():\n    pass\n')

            cli_module.main(['atasks', 'refs', source_path + '=remote.tasks'])

            with open(os.path.join(directory, 'tasks_refs.py'), encoding='utf-8') as references_file:
                references = references_file.read()

        self.assertIn("work = ataskref['remote.tasks.work']", references)

    def test_cli_refs_output_dir_preserves_source_relative_path(self):
        """The output directory contains the generated file at SOURCE's relative path."""
        with TemporaryDirectory() as directory:
            package = os.path.join(directory, 'app', 'workers')
            os.makedirs(package)
            source_path = os.path.join(package, 'tasks.py')
            with open(source_path, 'w', encoding='utf-8') as source_file:
                source_file.write('@atask\nasync def work():\n    pass\n')
            previous_directory = os.getcwd()
            try:
                os.chdir(directory)
                cli_module.main(['atasks', 'refs', 'app/workers/tasks.py', '--output-dir', 'generated'])
            finally:
                os.chdir(previous_directory)

            output_path = os.path.join(directory, 'generated', 'app', 'workers', 'tasks_refs.py')
            self.assertTrue(os.path.isfile(output_path))
            self.assertFalse(os.path.exists(os.path.join(package, 'tasks_refs.py')))
            with open(output_path, encoding='utf-8') as references_file:
                references = references_file.read()

        self.assertIn('# Generated by atasks refs from app/workers/tasks.py.', references)
        self.assertIn("work = ataskref['app.workers.tasks.work']", references)

    def test_cli_refs_output_file_combines_multiple_sources(self):
        """The output file contains references from every source module."""
        with TemporaryDirectory() as directory:
            first_path = os.path.join(directory, 'first.py')
            second_path = os.path.join(directory, 'second.py')
            for source_path, function_name in ((first_path, 'first_task'), (second_path, 'second_task')):
                with open(source_path, 'w', encoding='utf-8') as source_file:
                    source_file.write('@atask\nasync def %s():\n    pass\n' % function_name)
            previous_directory = os.getcwd()
            try:
                os.chdir(directory)
                cli_module.main([
                    'atasks', 'refs', 'first.py', 'second.py',
                    '--output-file', 'generated/references.py',
                ])
            finally:
                os.chdir(previous_directory)

            output_path = os.path.join(directory, 'generated', 'references.py')
            self.assertTrue(os.path.isfile(output_path))
            self.assertFalse(os.path.exists(os.path.join(directory, 'first_refs.py')))
            self.assertFalse(os.path.exists(os.path.join(directory, 'second_refs.py')))
            with open(output_path, encoding='utf-8') as references_file:
                references = references_file.read()

        self.assertIn('# Generated by atasks refs from these source files:', references)
        self.assertIn('# - first.py', references)
        self.assertIn('# - second.py', references)
        self.assertIn("first_task = ataskref['first.first_task']", references)
        self.assertIn("second_task = ataskref['second.second_task']", references)

    def test_cli_help_matches_root_help(self):
        """The ``help`` subcommand remains an alias for the root help output."""
        root_help = StringIO()
        with redirect_stdout(root_help):
            with self.assertRaises(SystemExit) as root_exit:
                cli_module.main(['atasks', '--help'])

        command_help = StringIO()
        with redirect_stdout(command_help):
            cli_module.main(['atasks', 'help'])

        self.assertEqual(root_exit.exception.code, 0)
        self.assertEqual(command_help.getvalue(), root_help.getvalue())

    def test_cli_help_describes_subcommands(self):
        """Root help explains the purpose of each supported subcommand."""
        output = StringIO()
        with redirect_stdout(output):
            with self.assertRaises(SystemExit):
                cli_module.main(['atasks', '--help'])

        help_text = ' '.join(output.getvalue().split())
        self.assertIn('serve their declared tasks', help_text)
        self.assertIn('lightweight references to declared tasks', help_text)

    def test_cli_subcommand_help_includes_subcommand_in_usage(self):
        """Delegated command help retains the command name without its executable path."""
        for command in ('service', 'refs'):
            output = StringIO()
            with redirect_stdout(output):
                with self.assertRaises(SystemExit) as error:
                    cli_module.main(['/usr/local/bin/atasks', command, '--help'])

            self.assertEqual(error.exception.code, 0)
            self.assertTrue(output.getvalue().startswith('usage: atasks %s ' % command))

    async def test_run_scenario_end_to_end(self):
        """Regression/integration test: a 'server' namespace paired with the
        loopback transport is the single-process combination that replaces
        the old ``-M loopback`` mode (see dev/tests/scenarios.py's aiomain) -
        its Router gets activated, the scenario module's own calls are
        exercised against it (raising AssertionError on the way out through
        asyncio.gather() if anything about the request/response round trip is
        wrong), and this only returns because ``_stop_soon()`` above stands in
        for a signal.
        """
        stopper = asyncio.ensure_future(_stop_soon())
        try:
            await aiomain(
                namespaces=[_ns('default', mode='server')],
                scenario=['dev.tests.scenarios'],
                opt=None,
            )
        finally:
            await stopper

    async def test_run_connect_disconnect_symmetry(self):
        """Regression test: ``aiomain()`` must disconnect whatever transport it
        connects, even with zero scenarios to run - otherwise a real transport
        (e.g. AMQPTransport) leaves background tasks dangling for the interpreter
        to tear down out of order on exit, instead of a clean shutdown. See the
        reported ``python -m atasks.commands.service -N mode=client,transport=amqp`` shutdown
        noise ("Task was destroyed but it is pending!" / "Event loop is closed").

        Stands in for a real AMQP-backed run (which needs a broker, see
        test_009_run_shutdown.py) by monkeypatching a call-recording transport in
        place of AMQPTransport - this only needs to prove ``connect``/``disconnect``
        are called in strictly matching pairs regardless of transport identity, and
        (for the 'server' namespace, once actually activated) that so are
        ``_register_request_callback``/``_unregister_request_callback``.
        """
        calls = []

        class RecordingTransport(LoopbackTransport):
            def __init__(self, url=None, **kwargs):
                # Accept (and ignore) the 'url' kwarg service.py passes for transport=amqp.
                super().__init__(**kwargs)

            async def connect(self):
                calls.append('connect')
                await super().connect()

            async def disconnect(self):
                calls.append('disconnect')
                await super().disconnect()

            async def _register_request_callback(self, name, callback):
                calls.append('register:' + name)
                await super()._register_request_callback(name, callback)

            async def _unregister_request_callback(self, name):
                calls.append('unregister:' + name)
                await super()._unregister_request_callback(name)

        with patch('atasks.transport.backends.amqp.AMQPTransport', RecordingTransport):
            await aiomain(namespaces=[_ns('default', transport='amqp')], scenario=[], opt=None)
        self.assertEqual(calls, ['connect', 'disconnect'])

        calls.clear()
        stopper = asyncio.ensure_future(_stop_soon())
        with patch('atasks.transport.backends.amqp.AMQPTransport', RecordingTransport):
            try:
                # No scenario module is passed on this particular run - but the
                # 'default' namespace's registries are process-global and persist
                # for the life of the test run, so whatever an *earlier* test
                # (e.g. test_run_scenario_end_to_end, or test_004_router.py)
                # already registered into 'default' is still there and still gets
                # (un)registered here. What must hold regardless of that history:
                # connect is first, disconnect is last, and every name registered
                # during activate() is unregistered exactly once during deactivate().
                await aiomain(namespaces=[_ns('default', mode='server', transport='amqp')], scenario=[], opt=None)
            finally:
                await stopper
        self.assertEqual(calls[0], 'connect')
        self.assertEqual(calls[-1], 'disconnect')
        registered = [c[len('register:'):] for c in calls if c.startswith('register:')]
        unregistered = [c[len('unregister:'):] for c in calls if c.startswith('unregister:')]
        self.assertEqual(sorted(registered), sorted(unregistered))

    async def test_run_activate_registers_and_deactivate_unregisters_every_atask(self):
        """With a real scenario module loaded, ``activate()``/``deactivate()``
        must (un)register a request callback for every ``@atask`` name it
        declares - one call each, never more, never fewer - and every
        registration must happen (during ``activate()``) strictly before every
        unregistration (during ``deactivate()``, at shutdown)."""
        calls = []

        class RecordingTransport(LoopbackTransport):
            def __init__(self, url=None, **kwargs):
                super().__init__(**kwargs)

            async def _register_request_callback(self, name, callback):
                calls.append(('register', name))
                await super()._register_request_callback(name, callback)

            async def _unregister_request_callback(self, name):
                calls.append(('unregister', name))
                await super()._unregister_request_callback(name)

        stopper = asyncio.ensure_future(_stop_soon())
        with patch('atasks.transport.backends.amqp.AMQPTransport', RecordingTransport):
            try:
                await aiomain(
                    namespaces=[_ns('default', mode='server', transport='amqp')],
                    scenario=['dev.tests.scenarios'],
                    opt=None,
                )
            finally:
                await stopper

        registered = [name for (op, name) in calls if op == 'register']
        unregistered = [name for (op, name) in calls if op == 'unregister']
        self.assertTrue(registered, 'expected at least one @atask to be registered')
        self.assertEqual(sorted(registered), sorted(unregistered))
        self.assertEqual(len(registered), len(set(registered)), 'no name should be registered twice')
        last_register_index = max(i for i, (op, _) in enumerate(calls) if op == 'register')
        first_unregister_index = min(i for i, (op, _) in enumerate(calls) if op == 'unregister')
        self.assertLess(last_register_index, first_unregister_index)
