[tox]
envlist = py310,py311,py312,py313,py314,py315,stylecheck

[testenv]
commands = python -m unittest discover -s dev -v
install_requires = 'setuptools>=40.8.0,<90' wheel
passenv =
    ATASKS_TEST_AMQP_URL
    ATASKS_TEST_AMQP_MANAGEMENT_URL
    ATASKS_TEST_AMQP_MANAGEMENT_USER
    ATASKS_TEST_AMQP_MANAGEMENT_PASSWORD
deps =
    backoff
[testenv:stylecheck]
commands =
    isort . --check
    flake8
    pydocstyle
deps =
    isort
    flake8
    pydocstyle

[flake8]
ignore = F403,W191,E124,E126,E128
max-line-length = 160
exclude =
    .*/
    *.egg-info/
    dev/manage.py
    migrations
    wheels/
    dist/
    build/
    dev/tests/settings.py
    setup.py

[isort]
indent=4
combine_star=1
combine_as_imports=1
include_trailing_comma=1
multi_line_output=3
lines_after_imports=2
known_future_library=future
default_section=THIRDPARTY
sections=FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER
skip_glob=*migrations*,*.egg-info
skip=.eggs,.venv,.tox,dist,build,wheels,setup.py

[pydocstyle]
inherit = false
select = D100, D101, D102, D103, D104, D107
match = (?!manage)(?!settings)(?!setup)((?!\d{4}_).*)\.py
match-dir = (atasks|dev)
