"""Generate lightweight references for tasks declared in a Python module."""
import argparse
import ast
import os
import sys


_DECORATOR_REFS = {
    'atask': 'ataskref',
    'atask_queue': 'atask_qref',
    'atask_broadcast': 'atask_bref',
}


def _decorator_info(decorator):
    """Return the matching reference factory and literal decorator options."""
    if isinstance(decorator, ast.Name):
        decorator_name = decorator.id
        keywords = []
    elif isinstance(decorator, ast.Call) and isinstance(decorator.func, ast.Name):
        decorator_name = decorator.func.id
        keywords = decorator.keywords
    else:
        return None

    ref_factory = _DECORATOR_REFS.get(decorator_name)
    if ref_factory is None:
        return None

    options = {}
    for keyword in keywords:
        if keyword.arg in ('name', 'namespace'):
            if not isinstance(keyword.value, ast.Constant) or not isinstance(keyword.value.value, str):
                raise ValueError('%s= must be a string literal' % keyword.arg)
            options[keyword.arg] = keyword.value.value
    return ref_factory, options


def _task_references(source, module_name):
    """Extract task reference definitions from Python ``source``."""
    tree = ast.parse(source)
    references = []
    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        for decorator in node.decorator_list:
            decorator_info = _decorator_info(decorator)
            if decorator_info is None:
                continue
            ref_factory, options = decorator_info
            task_name = options.get('name', '%s.%s' % (module_name, node.name))
            namespace = options.get('namespace')
            references.append((node.name, ref_factory, task_name, namespace))
            break
    return references


def _default_module_name(source_path):
    """Derive the import name for ``source_path`` relative to the current directory."""
    relative_path = os.path.relpath(source_path, os.getcwd())
    stem, extension = os.path.splitext(relative_path)
    if extension != '.py' or stem.startswith('..' + os.sep) or stem == '..':
        raise ValueError('source must be a Python file below the current directory')
    parts = stem.split(os.sep)
    if parts[-1] == '__init__':
        parts.pop()
    if not parts or any(not part.isidentifier() for part in parts):
        raise ValueError('cannot derive a Python module name from %r' % source_path)
    return '.'.join(parts)


def _render_references(references, source_paths):
    """Render extracted references as a standalone Python source file."""
    if len(source_paths) == 1:
        source_header = ['# Generated by atasks refs from %s.' % source_paths[0]]
    else:
        source_header = ['# Generated by atasks refs from these source files:']
        source_header.extend('# - %s' % source_path for source_path in source_paths)
    lines = source_header + [
        '# This file contains lightweight references to the tasks declared there.',
        '# Do not edit this file: changes will be overwritten by the next generation.',
        '',
        'from atasks.refs import atask_bref, atask_qref, ataskref',
        '',
    ]
    for function_name, ref_factory, task_name, namespace in references:
        factory = ref_factory
        if namespace is not None:
            factory += '(namespace=%r)' % namespace
        lines.append('%s = %s[%r]' % (function_name, factory, task_name))
    return '\n'.join(lines) + '\n'


def _relative_source_path(source_path):
    """Return ``source_path`` relative to the current directory when possible."""
    relative_path = os.path.relpath(source_path, os.getcwd())
    if relative_path.startswith('..' + os.sep) or relative_path == '..':
        raise ValueError('source must be a Python file below the current directory')
    return relative_path


def _write_references(output_path, references, source_paths):
    """Write rendered ``references`` to ``output_path``."""
    output_directory = os.path.dirname(output_path)
    if output_directory:
        os.makedirs(output_directory, exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as output_file:
        output_file.write(_render_references(references, source_paths))


def _source_specification(source_spec):
    """Split one ``SOURCE`` or ``SOURCE=MODULE`` command-line value."""
    source_path, separator, module_name = source_spec.partition('=')
    if not source_path:
        raise ValueError('source path must not be empty')
    if separator and not module_name:
        raise ValueError('module name must not be empty after =')
    return source_path, module_name or None


def generate(source_specs, output_dir=None, output_file=None):
    """Generate references for one or more source paths and return their output path or paths."""
    if isinstance(source_specs, str):
        source_specs = [source_specs]
    if not source_specs:
        raise ValueError('at least one source file is required')
    if output_dir is not None and output_file is not None:
        raise ValueError('--output-dir and --output-file cannot be used together')

    source_paths = []
    for source_spec in source_specs:
        source_path, module_name = _source_specification(source_spec)
        source_paths.append((os.path.abspath(source_path), module_name))
    absolute_paths = [source_path for source_path, _ in source_paths]
    if len(set(absolute_paths)) != len(absolute_paths):
        raise ValueError('each source file may be given only once')

    parsed_sources = []
    for source_path, module_name in source_paths:
        if not source_path.endswith('.py'):
            raise ValueError('source must have a .py extension')
        if module_name is None:
            module_name = _default_module_name(source_path)
        with open(source_path, encoding='utf-8') as source_file:
            references = _task_references(source_file.read(), module_name)
        parsed_sources.append((source_path, references))

    if output_file is not None:
        output_path = os.path.abspath(output_file)
        if output_path in absolute_paths:
            raise ValueError('--output-file must not overwrite a source file')
        references = [reference for _, source_references in parsed_sources for reference in source_references]
        reference_names = [reference[0] for reference in references]
        if len(set(reference_names)) != len(reference_names):
            raise ValueError('--output-file cannot combine references with duplicate function names')
        descriptions = [_relative_source_path(source_path) for source_path, _ in parsed_sources]
        _write_references(output_path, references, descriptions)
        return output_path

    output_paths = []
    for source_path, references in parsed_sources:
        if output_dir is None:
            output_path = source_path[:-3] + '_refs.py'
            description = source_path
        else:
            relative_path = _relative_source_path(source_path)
            output_path = os.path.join(os.path.abspath(output_dir), relative_path[:-3] + '_refs.py')
            description = relative_path
        _write_references(output_path, references, [description])
        output_paths.append(output_path)
    return output_paths[0] if len(output_paths) == 1 else output_paths


def main(argv=None):
    """Run the ``atasks refs`` command."""
    parser = argparse.ArgumentParser(
        prog=argv[0] if argv is not None else None,
        formatter_class=argparse.RawTextHelpFormatter,
        description='Generate a _refs.py module with lightweight references for tasks declared in SOURCE.',
    )
    parser.add_argument(
        'source',
        nargs='+',
        help='Python module(s) to inspect; use SOURCE=MODULE to override a module name',
    )
    output_group = parser.add_mutually_exclusive_group()
    output_group.add_argument(
        '--output-dir',
        help='directory for generated files; preserves SOURCE path relative to the current directory',
    )
    output_group.add_argument(
        '--output-file',
        help='single file that combines references generated from every SOURCE',
    )
    options = parser.parse_args(argv[1:] if argv is not None else None)
    try:
        generate(options.source, options.output_dir, options.output_file)
    except (OSError, SyntaxError, ValueError) as error:
        parser.error(str(error))


if __name__ == '__main__':
    sys.path.insert(0, '..')
    main(sys.argv)
